use crate::config::Severity;

#[allow(dead_code)]
pub enum RuleCategory {
    LanguageTypescript,
    SourceHygiene,
    ExportModuleShape,
    FileDirectory,
    Domain,
    Import,
}

#[allow(dead_code)]
pub struct RuleMetadata {
    pub id: &'static str,
    pub category: RuleCategory,
    pub default_severity: Severity,
    pub known_options: &'static [&'static str],
    pub conflicts: &'static [&'static str],
}

pub fn all_rule_metadata() -> &'static [RuleMetadata] {
    RULE_METADATA
}

pub fn known_option_names_for_rule(rule_id: &str) -> Option<&'static [&'static str]> {
    RULE_METADATA
        .iter()
        .find(|meta| meta.id == rule_id)
        .map(|meta| meta.known_options)
}

const RULE_METADATA: &[RuleMetadata] = &[
    RuleMetadata {
        id: "boolean-prefix",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "prefixes", "ignore-constants"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "component-file-only-components",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "directory-must-have-barrel",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &["no-barrel-files"],
    },
    RuleMetadata {
        id: "entry-file-no-logic",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "entry-files"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "explicit-return-type",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "hook-no-jsx",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "hook-prefix",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "prefixes"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "layer-boundaries",
        category: RuleCategory::Import,
        default_severity: Severity::Off,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "max-directory-depth",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth", "ignore-dirs"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "max-file-exports",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-exports"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "max-function-params",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-params"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "max-items-per-directory",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-items", "ignore-dirs", "count-folders"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "min-items-per-directory",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "min-items", "ignore-dirs", "count-folders"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-abbreviations",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "extra-abbreviations"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-anemic-domain",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-files", "ignore-dirs"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-any",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity", "allowed-folders"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-barrel-chain",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-barrel-files",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &["directory-must-have-barrel"],
    },
    RuleMetadata {
        id: "no-circular-import",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-comments",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-doc-comments"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-console",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-patterns"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-debugger",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-default-export",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity", "components-only"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-dump-files",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "extra-names"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-duplicate-file-names",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-names"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-empty-directories",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-dirs"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-empty-domain",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-dirs"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-empty-interface",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Error,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-enums",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-eval",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-export-star",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-focused-test",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-god-domain",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-files", "ignore-dirs"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-inline-types",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-interface",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-declaration-merging"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-large-file",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-lines"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-logic-in-barrel",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-logic-in-domain",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-magic-numbers",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allowed-numbers"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-mutable-exports",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-namespace",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-nested-functions",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-non-null-assertion",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-orphan-files",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "entry-files"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-package-cycle",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-private-package-import",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-process-env",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-restricted-imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "restricted"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-silent-catch",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-skipped-test",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-test-code-in-production",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-test-import",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-then-chain",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-type-assertion",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "no-upward-import",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "prefer-readonly",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
    },
    RuleMetadata {
        id: "prefer-satisfies",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Info,
        known_options: &["severity"],
        conflicts: &[],
    },
];
