use crate::config::Severity;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RuleCategory {
    LanguageTypescript,
    SourceHygiene,
    ExportModuleShape,
    FileDirectory,
    Domain,
    Import,
}

impl RuleCategory {
    pub fn as_str(&self) -> &'static str {
        match self {
            RuleCategory::LanguageTypescript => "typescript",
            RuleCategory::SourceHygiene => "hygiene",
            RuleCategory::ExportModuleShape => "exports",
            RuleCategory::FileDirectory => "files",
            RuleCategory::Domain => "domain",
            RuleCategory::Import => "imports",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[allow(dead_code)]
pub enum RuleAnalysisKind {
    Ast,
    ImportGraph,
    DirectoryInventory,
    SourceText,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FixCapability {
    None,
    Safe,
    Conditional,
}

#[allow(dead_code)]
pub struct RuleMetadata {
    pub id: &'static str,
    pub title: &'static str,
    pub category: RuleCategory,
    pub default_severity: Severity,
    pub known_options: &'static [&'static str],
    pub conflicts: &'static [&'static str],
    pub fix_capability: FixCapability,
    pub analysis_kind: RuleAnalysisKind,
}

pub fn all_rule_metadata() -> &'static [RuleMetadata] {
    RULE_METADATA
}

pub fn rule_by_id(rule_id: &str) -> Option<&'static RuleMetadata> {
    RULE_METADATA.iter().find(|meta| meta.id == rule_id)
}

pub fn known_option_names_for_rule(rule_id: &str) -> Option<&'static [&'static str]> {
    RULE_METADATA
        .iter()
        .find(|meta| meta.id == rule_id)
        .map(|meta| meta.known_options)
}

const RULE_METADATA: &[RuleMetadata] = &[
    RuleMetadata {
        id: "boolean-prefix",
        title: "Boolean prefix convention",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "prefixes", "ignore-constants"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "component-file-only-components",
        title: "Component-only exports",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "directory-must-have-barrel",
        title: "Require barrel files",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &["no-barrel-files"],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "entry-file-no-logic",
        title: "No logic in entry files",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "entry-files"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "explicit-return-type",
        title: "Explicit return types",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "hook-no-jsx",
        title: "No JSX in hooks",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "hook-prefix",
        title: "Hook naming convention",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "prefixes"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "layer-boundaries",
        title: "Layer boundary enforcement",
        category: RuleCategory::Import,
        default_severity: Severity::Off,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "max-directory-depth",
        title: "Max directory depth",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth", "ignore-dirs"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "max-file-exports",
        title: "Max file exports",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-exports"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "max-function-params",
        title: "Max function parameters",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-params"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "max-items-per-directory",
        title: "Max items per directory",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-items", "ignore-dirs", "count-folders"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "min-items-per-directory",
        title: "Min items per directory",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "min-items", "ignore-dirs", "count-folders"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "no-abbreviations",
        title: "No abbreviations",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "extra-abbreviations"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-anemic-domain",
        title: "No anemic domains",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-files", "ignore-dirs"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "no-any",
        title: "No any type",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity", "allowed-folders"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-barrel-chain",
        title: "No barrel chains",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-barrel-files",
        title: "No barrel files",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &["directory-must-have-barrel"],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-circular-import",
        title: "No circular imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-comments",
        title: "No comments",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-doc-comments"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-console",
        title: "No console",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-patterns"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-debugger",
        title: "No debugger",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::Safe,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-default-export",
        title: "No default exports",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity", "components-only"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-dump-files",
        title: "No dump files",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "extra-names"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::SourceText,
    },
    RuleMetadata {
        id: "no-duplicate-file-names",
        title: "No duplicate file names",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-names"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::SourceText,
    },
    RuleMetadata {
        id: "no-empty-directories",
        title: "No empty directories",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-dirs"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "no-empty-domain",
        title: "No empty domains",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "ignore-dirs"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "no-empty-interface",
        title: "No empty interfaces",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Error,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::Conditional,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-enums",
        title: "No enums",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-eval",
        title: "No eval",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-export-star",
        title: "No export star",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-focused-test",
        title: "No focused tests",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::Safe,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-god-domain",
        title: "No god domains",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-files", "ignore-dirs"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::DirectoryInventory,
    },
    RuleMetadata {
        id: "no-inline-types",
        title: "No inline types",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-interface",
        title: "No interfaces",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity", "allow-declaration-merging"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-large-file",
        title: "No large files",
        category: RuleCategory::FileDirectory,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-lines"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::SourceText,
    },
    RuleMetadata {
        id: "no-logic-in-barrel",
        title: "No logic in barrels",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-logic-in-domain",
        title: "No logic in domains",
        category: RuleCategory::Domain,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::SourceText,
    },
    RuleMetadata {
        id: "no-magic-numbers",
        title: "No magic numbers",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "allowed-numbers"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-mutable-exports",
        title: "No mutable exports",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-namespace",
        title: "No namespaces",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-nested-functions",
        title: "No nested functions",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-non-null-assertion",
        title: "No non-null assertion",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-orphan-files",
        title: "No orphan files",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "entry-files"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-package-cycle",
        title: "No package cycles",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-private-package-import",
        title: "No private package imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-process-env",
        title: "No process.env",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-restricted-imports",
        title: "No restricted imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "restricted"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-silent-catch",
        title: "No silent catch",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-skipped-test",
        title: "No skipped tests",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::Safe,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-test-code-in-production",
        title: "No test code in production",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-test-import",
        title: "No test imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "no-then-chain",
        title: "No then chains",
        category: RuleCategory::SourceHygiene,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-type-assertion",
        title: "No type assertions",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "no-upward-import",
        title: "No upward imports",
        category: RuleCategory::Import,
        default_severity: Severity::Warn,
        known_options: &["severity", "max-depth"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::ImportGraph,
    },
    RuleMetadata {
        id: "prefer-readonly",
        title: "Prefer readonly",
        category: RuleCategory::ExportModuleShape,
        default_severity: Severity::Warn,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
    RuleMetadata {
        id: "prefer-satisfies",
        title: "Prefer satisfies",
        category: RuleCategory::LanguageTypescript,
        default_severity: Severity::Info,
        known_options: &["severity"],
        conflicts: &[],
        fix_capability: FixCapability::None,
        analysis_kind: RuleAnalysisKind::Ast,
    },
];
